### ISSUE TITLE
Readme missing link

### ISSUE THREAD

**Issue by davidcorrigan714** [jfrog/jfrog-registry-operator#19]
### Describe the bug

 [Insert link to Step-by-Step Guide on the KB here ].

### Current behavior

 [Insert link to Step-by-Step Guide on the KB here ].

### JFrog registry operator version

0

### Package manager info

0

### Git provider

Azure DevOps

### Operating system type and version

0

**Comment by oumkale** [comment]
Thank you for reporting @davidcorrigan714, We have fixed this issues in https://github.com/jfrog/jfrog-registry-operator/pull/23
